// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisaTelegramBot.Infrastructure.Persistence;

#nullable disable

namespace VisaTelegramBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913133544_AddChannelMessagesFlightDealsAndLanguage")]
    partial class AddChannelMessagesFlightDealsAndLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisaTelegramBot.Domain.ChannelMessages.ChannelMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ScheduledAtUtc")
                        .HasDatabaseName("IX_ChannelMessages_Scheduled")
                        .HasFilter("[Status] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ScheduledAtUtc"), new[] { "LockedUntilUtc" });

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_ChannelMessages_CreatedAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAtUtc", "Id"));

                    b.ToTable("ChannelMessages", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.FlightDeals.FlightDeal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Airline")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BookingUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ChannelMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("DealKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTimeOffset>("DepartureAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("FlightRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FoundAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Transfers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ChannelMessageId");

                    b.HasIndex("DealKey")
                        .IsUnique()
                        .HasDatabaseName("UX_FlightDeals_DealKey");

                    b.HasIndex("FlightRouteId");

                    b.HasIndex("FoundAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_FlightDeals_FoundAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("FoundAtUtc", "Id"));

                    b.HasIndex("Status", "FoundAtUtc")
                        .HasDatabaseName("IX_FlightDeals_Status_FoundAtUtc");

                    b.ToTable("FlightDeals", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.FlightDeals.FlightRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("bit");

                    b.Property<long>("CheckInterval")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MonthsAhead")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextCheckAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_FlightRoutes_CreatedAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAtUtc", "Id"));

                    b.HasIndex("IsActive", "NextCheckAtUtc")
                        .HasDatabaseName("IX_FlightRoutes_IsActive_NextCheckAtUtc");

                    b.ToTable("FlightRoutes", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsItems.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ArchiveReason")
                        .HasColumnType("int");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryLockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastDeliveryError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("NewsSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NextDeliveryAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NewsItems_ContentHash");

                    b.HasIndex("NextDeliveryAttemptAtUtc")
                        .HasDatabaseName("IX_NewsItems_Pending")
                        .HasFilter("[DeliveryStatus] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextDeliveryAttemptAtUtc"), new[] { "DeliveryLockedUntilUtc" });

                    b.HasIndex("DeliveryStatus", "DiscoveredAtUtc")
                        .HasDatabaseName("IX_NewsItems_DeliveryStatus_DiscoveredAtUtc");

                    b.HasIndex("DiscoveredAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_NewsItems_DiscoveredAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("DiscoveredAtUtc", "Id"));

                    b.HasIndex("NewsSourceId", "DiscoveredAtUtc")
                        .HasDatabaseName("IX_NewsItems_NewsSourceId_DiscoveredAtUtc");

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsSources.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FetchInterval")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordFilter")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastFetchError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastFetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSucceededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NextFetchAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParsingRules")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("TurkishOnly")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_NewsSources_CreatedAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAtUtc", "Id"));

                    b.HasIndex("IsActive", "NextFetchAtUtc")
                        .HasDatabaseName("IX_NewsSources_IsActive_NextFetchAtUtc");

                    b.ToTable("NewsSources", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.ChannelMessages.ChannelMessage", b =>
                {
                    b.OwnsOne("VisaTelegramBot.Domain.ChannelMessages.MessageButton", "Button", b1 =>
                        {
                            b1.Property<Guid>("ChannelMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("ButtonText");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)")
                                .HasColumnName("ButtonUrl");

                            b1.HasKey("ChannelMessageId");

                            b1.ToTable("ChannelMessages");

                            b1.WithOwner()
                                .HasForeignKey("ChannelMessageId");
                        });

                    b.OwnsOne("VisaTelegramBot.Domain.ChannelMessages.MessagePhoto", "Photo", b1 =>
                        {
                            b1.Property<Guid>("ChannelMessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("PhotoContent");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("PhotoContentType");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PhotoFileName");

                            b1.HasKey("ChannelMessageId");

                            b1.ToTable("ChannelMessages");

                            b1.WithOwner()
                                .HasForeignKey("ChannelMessageId");
                        });

                    b.Navigation("Button");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.FlightDeals.FlightDeal", b =>
                {
                    b.HasOne("VisaTelegramBot.Domain.ChannelMessages.ChannelMessage", null)
                        .WithMany()
                        .HasForeignKey("ChannelMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VisaTelegramBot.Domain.FlightDeals.FlightRoute", null)
                        .WithMany()
                        .HasForeignKey("FlightRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsItems.NewsItem", b =>
                {
                    b.HasOne("VisaTelegramBot.Domain.NewsSources.NewsSource", null)
                        .WithMany()
                        .HasForeignKey("NewsSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
