// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VisaTelegramBot.Infrastructure.Persistence;

#nullable disable

namespace VisaTelegramBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921192028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VisaTelegramBot.Domain.ChannelMessages.ChannelMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("character varying(3500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAtUtc")
                        .HasDatabaseName("IX_ChannelMessages_Scheduled")
                        .HasFilter("\"Status\" = 1");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ScheduledAtUtc"), new[] { "LockedUntilUtc" });

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("IX_ChannelMessages_CreatedAtUtc_Id");

                    b.ToTable("ChannelMessages", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsItems.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("ArchiveReason")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeliveryLockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastDeliveryError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("NewsSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NextDeliveryAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NewsItems_ContentHash");

                    b.HasIndex("NextDeliveryAttemptAtUtc")
                        .HasDatabaseName("IX_NewsItems_Pending")
                        .HasFilter("\"DeliveryStatus\" = 1");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextDeliveryAttemptAtUtc"), new[] { "DeliveryLockedUntilUtc" });

                    b.HasIndex("DeliveryStatus", "DiscoveredAtUtc")
                        .HasDatabaseName("IX_NewsItems_DeliveryStatus_DiscoveredAtUtc");

                    b.HasIndex("DiscoveredAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsItems_DiscoveredAtUtc_Id");

                    b.HasIndex("NewsSourceId", "DiscoveredAtUtc")
                        .HasDatabaseName("IX_NewsItems_NewsSourceId_DiscoveredAtUtc");

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsSources.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FetchInterval")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeywordFilter")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("LastFetchError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastFetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSucceededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NextFetchAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParsingRules")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("TurkishOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsSources_CreatedAtUtc_Id");

                    b.HasIndex("IsActive", "NextFetchAtUtc")
                        .HasDatabaseName("IX_NewsSources_IsActive_NextFetchAtUtc");

                    b.ToTable("NewsSources", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.ChannelMessages.ChannelMessage", b =>
                {
                    b.OwnsOne("VisaTelegramBot.Domain.ChannelMessages.MessageButton", "Button", b1 =>
                        {
                            b1.Property<Guid>("ChannelMessageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("ButtonText");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("ButtonUrl");

                            b1.HasKey("ChannelMessageId");

                            b1.ToTable("ChannelMessages");

                            b1.WithOwner()
                                .HasForeignKey("ChannelMessageId");
                        });

                    b.OwnsOne("VisaTelegramBot.Domain.ChannelMessages.MessagePhoto", "Photo", b1 =>
                        {
                            b1.Property<Guid>("ChannelMessageId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Content")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("PhotoContent");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PhotoContentType");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("PhotoFileName");

                            b1.HasKey("ChannelMessageId");

                            b1.ToTable("ChannelMessages");

                            b1.WithOwner()
                                .HasForeignKey("ChannelMessageId");
                        });

                    b.Navigation("Button");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsItems.NewsItem", b =>
                {
                    b.HasOne("VisaTelegramBot.Domain.NewsSources.NewsSource", null)
                        .WithMany()
                        .HasForeignKey("NewsSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
