// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisaTelegramBot.Infrastructure.Persistence;

#nullable disable

namespace VisaTelegramBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913114357_AddNewsSourceKeywordFilter")]
    partial class AddNewsSourceKeywordFilter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsItems.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryLockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastDeliveryError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("NewsSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NextDeliveryAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("UX_NewsItems_ContentHash");

                    b.HasIndex("NextDeliveryAttemptAtUtc")
                        .HasDatabaseName("IX_NewsItems_Pending")
                        .HasFilter("[DeliveryStatus] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextDeliveryAttemptAtUtc"), new[] { "DeliveryLockedUntilUtc" });

                    b.HasIndex("DeliveryStatus", "DiscoveredAtUtc")
                        .HasDatabaseName("IX_NewsItems_DeliveryStatus_DiscoveredAtUtc");

                    b.HasIndex("DiscoveredAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_NewsItems_DiscoveredAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("DiscoveredAtUtc", "Id"));

                    b.HasIndex("NewsSourceId", "DiscoveredAtUtc")
                        .HasDatabaseName("IX_NewsItems_NewsSourceId_DiscoveredAtUtc");

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsSources.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FetchInterval")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordFilter")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastFetchError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastFetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSucceededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NextFetchAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParsingRules")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsUnique()
                        .HasDatabaseName("CIX_NewsSources_CreatedAtUtc_Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedAtUtc", "Id"));

                    b.HasIndex("IsActive", "NextFetchAtUtc")
                        .HasDatabaseName("IX_NewsSources_IsActive_NextFetchAtUtc");

                    b.ToTable("NewsSources", (string)null);
                });

            modelBuilder.Entity("VisaTelegramBot.Domain.NewsItems.NewsItem", b =>
                {
                    b.HasOne("VisaTelegramBot.Domain.NewsSources.NewsSource", null)
                        .WithMany()
                        .HasForeignKey("NewsSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
